debug.srp created srp.log for error report...
runtime exception handler called
exception is: type error, expected Object
frame variables: {}
frame pc: -1
frame method: <callin_method>
frame class: nil

Debugger invoked.
-----------------------------------------------------
Method <callin_method> in class nil
-----------------------------------------------------
Method <immediate command 0> in class nil, char 3333 in file 
    C:\Users\georg\Documents\GitHub\benchmarks\bedcov.srp
Frame variables: {i: 0}
 117:     main(10)
              ^
-----------------------------------------------------
Method main in class nil, char 2631 in file 
    C:\Users\georg\Documents\GitHub\benchmarks\bedcov.srp
Frame variables: {arg: 10, i: 0, item: nil}
  95:                 b = iit_overlap(a1, max_level, st1, en1)
                                     ^
-----------------------------------------------------
Method iit_overlap in class nil, char 934 in file 
    C:\Users\georg\Documents\GitHub\benchmarks\bedcov.srp
Frame variables: {a: [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...], max_level: 19, start: 0, end: 0}
  34:         t = stack.pop()
                           ^
-----------------------------------------------------
Method <callin_method> in class nil
type error, expected Object
1> 
